language: generic

before_install:
  - "if [[ \"$TRAVIS_OS_NAME\" == \"osx\" ]]; then gem install xcpretty -N --no-ri --no-rdoc ; fi"

git:
  submodules: false

matrix:
  include:
    - 
      os: linux
      dist: trusty
      sudo: required
      script: "echo swift build"
    - 
      os: osx
      osx_image: xcode8
      script: "echo \"xcodebuild -destination platform=iOS Simulator,OS=10.0,name=iPhone 6s -sdk iphonesimulator\""
    - 
      os: osx
      osx_image: xcode8
      script: "echo \"xcodebuild -destination platform=OS X,arch=x86_64 -sdk macosx\""
