language: generic

before_install:
  - if [[ \"$TRAVIS_OS_NAME\" == \"osx\" ]]; then gem install xcpretty -N --no-ri --no-rdoc ; fi

git:
  submodules: false

matrix:
  include:
    - 
      os: linux
      dist: trusty
      sudo: required
    - 
      os: osx
      osx_image: xcode8
      env: 
         - SCHEME=TraceLog-iOS-Example 
         - TEST_DEST="platform=iOS Simulator,OS=10.0,name=iPhone 6s" 
         - TEST_SDK=iphonesimulator
    - 
      os: osx
      osx_image: xcode8
      env: 
         - SCHEME=TraceLog-iOS-Example 
         - TEST_DEST="platform=iOS Simulator,OS=10.0,name=iPhone 6" 
         - TEST_SDK=iphonesimulator
    - 
      os: osx
      osx_image: xcode8
      env: 
         - SCHEME=TraceLog-iOS-Example 
         - TEST_DEST="platform=iOS Simulator,OS=9.3,name=iPhone 6" 
         - TEST_SDK=iphonesimulator
    - 
      os: osx
      osx_image: xcode8
      env: 
         - SCHEME=TraceLog-iOS-Example 
         - TEST_DEST="platform=iOS Simulator,OS=9.2,name=iPhone 5s" 
         - TEST_SDK=iphonesimulator
    - 
      os: osx
      osx_image: xcode8
      env: 
         - SCHEME=TraceLog-iOS-Example 
         - TEST_DEST="platform=iOS Simulator,OS=9.0,name=iPhone 4s" 
         - TEST_SDK=iphonesimulator
    - 
      os: osx
      osx_image: xcode8
      env: 
         - SCHEME=TraceLog-OSX-Example 
         - TEST_DEST="platform=OS X,arch=x86_64" 
         - TEST_SDK=macosx
         
script:
  - if [[ \"$TRAVIS_OS_NAME\" == \"osx\" ]]; then echo "xcodebuild clean test -workspace Example/TraceLog.xcworkspace -scheme \"$SCHEME\" -destination \"$TEST_DEST\" -sdk \"$TEST_SDK\" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty" ; fi
  - if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then echo "swift build" ; fi
  
after_success:
  - echo "bash <(curl -s https://codecov.io/bash)"
