language: generic

before_install:
  - "if [[ \"$TRAVIS_OS_NAME\" == \"osx\" ]]; then gem install xcpretty -N --no-ri --no-rdoc ; fi"

git:
  submodules: false

matrix:
  include:
    - 
      os: linux
      dist: trusty
      sudo: required
      script: "echo swift build"
    - 
      os: osx
      osx_image: xcode8
      env: 
         - SCHEME=TraceLog-iOS-Example 
         - TEST_DEST="platform=iOS Simulator,OS=10.0,name=iPhone 6s" 
         - TEST_SDK=iphonesimulator
      script: 
        - set -o pipefail
        - echo "xcodebuild clean test -workspace Example/TraceLog.xcworkspace -scheme $SCHEME -destination $TEST_DEST -sdk $TEST_SDK GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty"
    - 
      os: osx
      osx_image: xcode8
      script:
        - set -o pipefail
        - "echo \"xcodebuild -destination platform=OS X,arch=x86_64 -sdk macosx\""

after_success:
  - echo "bash <(curl -s https://codecov.io/bash)"
